name: Index cargo contract check

on:
  push:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-contract-build:
    name: Run cargo contract build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install Binaryen
        run: "cd /tmp \
          && curl -OL https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz \
          && tar xf binaryen-version_110-x86_64-linux.tar.gz \
          && cp binaryen-version_110/bin/* /bin/ \
          && cp binaryen-version_110/include/* /usr/include \
          && cp binaryen-version_110/lib/* /lib/ \
          && rm -rf binaryen-version_110"
